# Generated by Django 4.2.6 on 2023-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_auto_20231014_2309"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
